name: ${plugin_name}
main: giselle.skript.custom_fishing.SkCustomFishing
version: ${plugin_version}
api-version: 1.15
depend: [ CustomFishing, Skript ]
website: ${plugin_homepage}
description: ${plugin_description}
authors: [ Gisellevonbingen ]
database: false
